# Generated by Django 4.2.30 on 2026-04-22 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rent', models.IntegerField()),
                ('deposit', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('wifi', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('gender_preference', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], default='any', max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pg_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
