# Generated by Django 4.2.30 on 2026-04-22 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_pg_image_pgimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pg',
            old_name='title',
            new_name='name',
        ),
    ]
