# Generated by Django 4.2.30 on 2026-04-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_title_pg_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='booking_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
