# Generated by Django 4.2.30 on 2026-04-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_pg_booking_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pg',
            name='id',
        ),
        migrations.AddField(
            model_name='pg',
            name='pg_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
