# Generated by Django 4.2.30 on 2026-04-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_pg_id_pg_pg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg',
            name='pg_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
