# Generated by Django 4.2.30 on 2026-04-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
