# Generated by Django 4.2.30 on 2026-04-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_requests_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
