# Generated by Django 4.2.30 on 2026-04-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_requests_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='pg_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
