# Generated by Django 4.2.30 on 2026-04-26 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_requests_pg_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='date',
            new_name='visit_date',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='time',
            new_name='visit_time',
        ),
        migrations.AddField(
            model_name='requests',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending'),
        ),
        migrations.AddField(
            model_name='requests',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
