# Generated by Django 4.2.30 on 2026-04-27 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_pg_pg_id'),
        ('requests', '0005_rename_date_requests_visit_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='pg_id',
        ),
        migrations.AddField(
            model_name='requests',
            name='pg',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='listings.pg'),
            preserve_default=False,
        ),
    ]
